appName: 'hello-world'
ecrRepository: 'hello-world'
ecrRegistry: '169889227629.dkr.ecr.us-west-2.amazonaws.com'
unitTestCommand: 'pip install -r hello_world/requirements.txt && tox'
snycTargetFile: 'hello_world/requirements.txt'
snykAdditionalArguments: '--command=python3'
functionalTestCommand: 'sleep 5 && tox -e behave'
fortifyAppId: '149890'
fortifyReleaseName: 'Dev'
pollFortifyResult: 'false'
manifestLocation: 'hello_world/requirements.txt'
change_cmdb_ci: '6ea21db51b3a88907375dc25cc4bcbf2'
change_assignment_group: '55db302f1b11f7488fec8663cc4bcb7f'
change_short_description: 'CI/CD Pipeline Request'
change_description: 'Production Deployment from CI/CD Pipeline'
change_justification: 'Project requirement'
change_pre_implementation_test_plan: 'Already tested in lower environment'
change_implementation_plan: 'Perform the deployment through CI/CD Pipeline'
change_test_plan: 'Perform the sanity testing of the application in Production environment'
change_backout_plan: 'Perform another deployment with previous deployed tag'
